# Generated by Django 3.0.4 on 2020-04-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=20)),
                ('fuel_count', models.DecimalField(decimal_places=1, max_digits=3)),
                ('color', models.CharField(max_length=20)),
                ('doors', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('minimum_age', models.IntegerField()),
                ('price', models.IntegerField()),
                ('transmission', models.CharField(blank=True, max_length=30)),
                ('ratings', models.IntegerField()),
                ('is_published', models.BooleanField(default=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('carmanager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carmanager.CarManager')),
            ],
        ),
    ]
